[[main]]
    identifier = "Posts"
    name = "文章"
    url = "/posts/"
    weight = 20

[[main]]
    identifier = "Archives"
    name = "归档"
    url = "/archives/"
    weight = 30

[[main]]
    identifier = "About"
    name = "关于"
    url = "/about/"
    weight = 50
