DateFormat = '2006-01-02'

# defaultTheme = 'auto'
# defaultTheme = 'light'
defaultTheme = 'dark'

ShowWordCount = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowAllPagesInArchive = true

cdnPrefix = "https://cdn.jsdelivr.net/gh/ilunp/ilunp@gh-pages"

[profileMode]
    enabled = true

    title = "ILUNP'S Blog"
    subtitle = 'æ•å¤´é‡Œè—æ»¡äº†å‘éœ‰çš„æ¢¦ï¼Œæ¢¦é‡Œä½æ»¡äº†æ— æ³•æ‹¥æŠ±çš„äººã€‚'
    imageUrl = 'https://avatars.githubusercontent.com/u/46992517?v=4'

    [[profileMode.buttons]]
        name = 'ğŸ–¼ï¸ Gallery!'
        url = 'gallery'

    [[socialIcons]]
        name = 'github'
        url = 'https://github.com/ilunp'

    [[socialIcons]]
        name = 'email'
        url = 'mailto:ilunp@qq.com'

    [[socialIcons]]
        name = 'rss'
        url = 'index.xml'